Run check_audio in python env
The documented command is missing the env and this is what happend:  

```
Traceback (most recent call last):
  File "checkpoints/check_audio.py", line 27, in <module>
    import aiy.audio  # noqa
ImportError: No module named 'aiy'
```

I changed it to the command that can be found in `shortcuts/check_audio.desktop`